# Generated by Django 2.2.14 on 2020-10-27 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0006_item_by_seller_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_home.Item')),
            ],
        ),
    ]
