# Generated by Django 2.2.14 on 2020-10-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0007_display2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(storage='media/media', upload_to='media/media'),
        ),
        migrations.AlterField(
            model_name='item_by_seller',
            name='image_by_seller',
            field=models.ImageField(storage='media/media', upload_to='media/media'),
        ),
    ]
