# Generated by Django 2.2.14 on 2020-11-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_home', '0011_auto_20201027_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='cal_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_product', models.CharField(max_length=100)),
                ('Category_price', models.FloatField()),
            ],
        ),
    ]
